### ISSUE TITLE
Unpublished pages don't get modified

### ISSUE THREAD

**Issue by jlahijani** [adrianbj/ProcessAdminActions#1]
Let's say I want to make a bunch of unpublished pages be published using the Page Manipulator action.  It won't work because the action doesn't use 'include=all' in the selector to find unpublished pages.

**Comment by adrianbj** [comment]
Just add the include = all in the selector options:

![screen shot 2016-12-24 at 6 20 44 pm](https://cloud.githubusercontent.com/assets/871211/21469485/baf76102-ca05-11e6-972f-afc60cb01535.png)


That was how I was expecting it would be used. Does this seem reasonable to you?

**Comment by adrianbj** [comment]
Hi @jlahijani - just wondering if I can close this issue - does my description above make sense and fulfill your needs?
