### ISSUE TITLE
Double-encoded entity in table header

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/ProcessAdminActions#12]
![2019-10-03_153503](https://user-images.githubusercontent.com/1538852/66095254-6670e880-e5f3-11e9-9a83-55981833d0b3.png)

See this issue for background of why double-encoding is happening: https://github.com/processwire/processwire-issues/issues/827

**Comment by adrianbj** [comment]
Thanks @Toutouwai - I couldn't see the issue in my install, but I changed it to use `sprintf` so hopefully that fixes it for you.

**Comment by Toutouwai** [comment]
Thanks, that fixes it here.
