### ISSUE TITLE
filemtime() warning on install

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/ProcessAdminActions#13]
Hi Adrian,

When installing the module Tracy picks up the following error:

```
PHP Warning: filemtime(): stat failed for .../site/assets/cache/AdminActions/AdminActionsBackup.sql in ...\ProcessAdminActions.module.php:390
```

**Comment by adrianbj** [comment]
Thanks @Toutouwai - should be fixed in the latest version. I fixed a couple of other things as well, and also added that data-path attribute that I mentioned via the PW forum PM message on March 15 if you want to use that in your "AddAdminAction" extension.

**Comment by Toutouwai** [comment]
Cool, thanks!
