### ISSUE TITLE
Rename execute query parameter to prevent firewall block

### ISSUE THREAD

**Issue by daun** [adrianbj/ProcessAdminActions#15]
On sites that have the [7G firewall](https://perishablepress.com/7g-firewall/) installed, requests get blocked when executing any action. The reason is that the firewall blocks URLs that have `exec` in the query string.

Could the query parameter be renamed from `execute` to something like `run`? Would this have any adverse effects?

Currently, I've removed the rule from the firewall, but maybe it's a small change that will make life easier for other users of those htaccess rules.

Happy to submit a PR.

**Comment by daun** [comment]
It might actually be a url `/execute/` not a query parameter. I'm a little foggy on the details.

**Comment by adrianbj** [comment]
I **think** the only changes that will be needed are to: 

1) change the name of this method: https://github.com/adrianbj/ProcessAdminActions/blob/5e47e3df45b427d7e05419137994bcf81286c17a/ProcessAdminActions.module.php#L202 to `executeRun()`

2) change the path here: https://github.com/adrianbj/ProcessAdminActions/blob/5e47e3df45b427d7e05419137994bcf81286c17a/ProcessAdminActions.module.php#L437 to `./run?action='.$this->action;`

Do you feel like making those changes at your end and doing a thorough test for me?

**Comment by daun** [comment]
Sure, I'll give it a go and report back with a PR.

**Comment by daun** [comment]
I opened PR #16 which would address this.

**Comment by adrianbj** [comment]
Thanks!
