### ISSUE TITLE
Fatal Error after fresh install, $this->data['core'] is null

### ISSUE THREAD

**Issue by MaxKoll** [adrianbj/ProcessAdminActions#18]
Hi,

it seems that after a fresh install `$this->data['core']` is null, so this line produces a fatal error:

https://github.com/adrianbj/ProcessAdminActions/blob/734568f91eab9f41804bc6d4ff78f2728b20d4ac/ProcessAdminActions.module.php#L702

I fixed it by changing it to:
`$installedCount = count($siteActionsDB) + count($this->data['core'] ?? array());`

Max

**Comment by adrianbj** [comment]
Thanks @MaxKoll - should be fixed in the latest version, although I did use `?:` instead of `??` to support older versions of PHP. I am pretty sure in this situation it should work just as well.
