### ISSUE TITLE
PHP8 deprecation warning

### ISSUE THREAD

**Issue by matjazpotocnik** [adrianbj/ProcessAdminActions#19]
PHP Deprecated: ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in [...\ProcessPageFieldSelectCreator\ProcessPageFieldSelectCreator.module.php:125]

**Comment by adrianbj** [comment]
Hi @matjazpotocnik - seems like this is posted to the wrong module's repo, but that said, I am wondering if this is a PW core bug - are you by chance running a recent (but not latest) dev version while there were some recently introduced module related bugs?

Can you try running this in Tracy console:
```
foreach($this->wire('modules')->get("InputfieldPage")->data['inputfieldClasses'] as $class) {
    $module = $this->wire('modules')->getModule($class, array('noInit' => true));
    $info = $this->wire('modules')->getModuleInfo($module);
    $label = ucfirst($info['title']);
    d($info, $label);
}
```
If there is one returned with an empty (null) title could you please expand the array of info and let me know what the problem module is. Perhaps it's just a missing `title` attribute on a module that needs fixing.

**Comment by matjazpotocnik** [comment]
Uh, ah, yes, wrong repo. I didn't have time to debug this further, was in a hurry, just opened an issue so that I don't forget. Sorry. That said, you'r right, it's a module with an empty array, don't know how could that be (I'm on PW 3.0.220):

```
'id' => 0
'name' => ''
'title' => null
'version' => 0
'versionStr' => '0.0.0'
'author' => ''
'summary' => 'Inactive'
'href' => ''
'icon' => ''
'requires' => array (0)
'requiresVersions' => array (0)
'installs' => array (0)
'permission' => ''
'permissions' => array (0)
'autoload' => null
'singular' => null
'created' => 0
'installed' => null
'configurable' => null
'searchable' => null
'namespace' => null
'file' => null
'core' => null
'error' => 'Unable to locate module'
```

Modules refresh doesn't help. It looks like something is wrong with my (abused) instalation, so I'll close this issue. Thanks for looking into it.
