### ISSUE TITLE
Error after updating to 0.3.4

### ISSUE THREAD

**Issue by ghost** [adrianbj/ProcessAdminActions#2]
Running ProcessWire 3.0.45, after updating to AdminActions 0.3.4, I get this error:

Unsupported operand types (line 347 in /home/*/public_html/site/modules/ProcessAdminActions/ProcessAdminActions.module) 

(Tried logging out/in, clearing compilated files and updating module files.)

**Comment by adrianbj** [comment]
Thanks @franctic-aerobic - I think it was likely a PHP version related issue, but the latest commit should fix it for you. Please close if everything is ok now.

**Comment by ghost** [comment]
Thanks, the latest commit fixed it.
