### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/ProcessAdminActions#20]
Hi Adrian,

We discussed this in the support topic a few years ago but we didn't find a resolution. 

The issue is that there's an error message if an action includes the PW namespace. Besides needing to have the namespace in order to get proper code analysis in an IDE, I also think that as a general principle we should be avoiding the PW file compiler whenever possible. The compiler made sense early on to ease the transition from PW2 to PW3 but coming up on 8 years later I think it's more bad than good and it's okay for module authors to now drop PW2 support.

I've attached a couple of test actions that demonstrate the error - one an installable module and the other for /site/templates/AdminActions/.

[AdminActionsTestOne.zip](https://github.com/adrianbj/ProcessAdminActions/files/14172288/AdminActionsTestOne.zip)
[TestTwo.action.zip](https://github.com/adrianbj/ProcessAdminActions/files/14172290/TestTwo.action.zip)

And these are the errors:
![2024-02-06_104439](https://github.com/adrianbj/ProcessAdminActions/assets/1538852/392333f0-2eae-466d-9b9a-e1cbc9ba6ddb)
![2024-02-06_104731](https://github.com/adrianbj/ProcessAdminActions/assets/1538852/7928f1f2-7c0c-457f-b6e1-b9c018b9c522)

**Comment by adrianbj** [comment]
Hi @Toutouwai ,

I want to help with this, but I am worried about breaking everyone's already existing custom (site) actions because if I namespace the module, I can't see a way for existing non-namespaced actions to work. Any ideas?

If you want to try a namespaced version, I have set up a new branch you can use to test. At the moment I haven't namespaced any of the included core actions, but the main module.php is namespaced and the calls to instantiate the actions have been updated so they will work with namespaced actions.

**Comment by adrianbj** [comment]
I played around with this which should work in PHP 7+ but it doesn't seem completely reliable.
```
                try {
                    require_once $this->getActionPath($actionName);
                    $nsClass = __NAMESPACE__ . '\\' . $actionName;
                }
                catch (\Error $e) {
                    require_once($this->wire('files')->compile($this->getActionPath($actionName)));
                    $nsClass = '\\' . $actionName;
                }
```

This version is available in namespaced-v2 if you're interested in seeing if you can figure out why it's working for some modules, seemingly any site modules namespaced or not, but not any core modules that aren't namespaced.

**Comment by Toutouwai** [comment]
Thanks for working on this. I agree that custom actions without a namespace would be a problem.

I think I'm experiencing the same problems you are when attempting to use the PW FileCompiler. It's like it compiles the first action correctly (e.g. it changes "extends ProcessAdminActions" to "extends \ProcessWire\ProcessAdminActions") but then it fails to do this for all the other actions in the loop. It just copies them to the FileCompiler cache but doesn't actually add any namespace and I can't work out why.

The best thing would be for users to add the namespace to their custom actions themselves. Maybe it would be sufficient to emphasise that it's a major version change and then show notices advising users to add the namespace to their custom actions. The notice could appear when the upgrade() method executes and when attempting to run an action without a namespace, by checking it first with $files->getNamespace(). Instead of the action form the user would see the notice.

Beyond this I had success with adding a custom compiler method to ProcessAdminActions (for the "namespaced-version" branch). This is much more basic than the PW FileCompiler and simply adds "namespace ProcessWire" to any action file that doesn't have a namespace. It allows old actions to continue to work until they are manually updated with the namespace.

Here's the new method if you want to try it out:

```php
protected function compile($actionPath) {
    $files = $this->wire()->files;
    $config = $this->wire()->config;
    $dir = $config->paths->cache . 'AdminActions/compiled/';
    if(!is_dir($dir)) $files->mkdir($dir);
    $parts = pathinfo($actionPath);
    $contents = $files->fileGetContents($actionPath);
    $contents = substr_replace($contents, ' namespace ProcessWire;', 5, 0);
    $filename = $dir . $parts['basename'];
    $files->filePutContents($filename, $contents);
    $this->wire()->warning(sprintf($this->_('An action file has been compiled to %s. Please consider adding the ProcessWire namespace to your action file to avoid automatic compilation.'), $config->urls->cache . 'AdminActions/compiled/' . $parts['basename']), Notice::noGroup);
    return $filename;
}
```

And the updated getActionPath() method:

```php
private function getActionPath($className) {
    $actionPath = false;
    if(file_exists($path = __DIR__ . '/actions/'.$className.'.action.php')) {
        $actionPath = $path;
    }
    elseif(file_exists($path = __DIR__ . '/actions/'.$className.'/'.$className.'.action.php')) {
        $actionPath = $path;
    }
    elseif(file_exists($path = $this->wire('config')->paths->templates.'AdminActions/'.$className.'.action.php')) {
        $actionPath = $path;
    }
    elseif(file_exists($path = $this->wire('config')->paths->templates.'AdminActions/'.$className.'/'.$className.'.action.php')) {
        $actionPath = $path;
    }
    elseif($this->wire('modules')->isInstalled('AdminActions'.$className)) {
        $actionPath = $this->wire('config')->paths->siteModules . 'AdminActions' . $className.'/'.$className.'.action.php';
    }
    if($actionPath) {
        $ns = $this->wire()->files->getNamespace($actionPath);
        if($ns === '\\') $actionPath = $this->compile($actionPath);
    }
    return $actionPath;
}
```

**Comment by Toutouwai** [comment]
Improved compile function:

```php
protected function compile($actionPath) {
    $files = $this->wire()->files;
    $config = $this->wire()->config;
    
    $dir = $config->paths->cache . 'AdminActions/compiled/';
    if(!is_dir($dir)) $files->mkdir($dir);

    $parts = pathinfo($actionPath);
    $filename = $dir . $parts['basename'];
    $modSource = filemtime($actionPath);
    $modDestination = is_file($filename) ? filemtime($filename) : 0;
    if($modDestination > $modSource) return $filename;

    $contents = $files->fileGetContents($actionPath);
    $contents = substr_replace($contents, ' namespace ProcessWire;', 5, 0);
    $files->filePutContents($filename, $contents);
    $this->wire()->warning(sprintf($this->_('An action file has been compiled to %s. Please consider adding the ProcessWire namespace to your action file to avoid automatic compilation.'), $config->urls->cache . 'AdminActions/compiled/' . $parts['basename']), Notice::noGroup);
    return $filename;
}
```

**Comment by adrianbj** [comment]
Thanks @Toutouwai - I like the idea of automatically just adding the namespace to the custom actions, but what do you think about simply modifying the original files, rather than making copies in the /compiled/ folder. I suppose there is a possibility that there won't have write access, but is that the only reason you went with the copies or is there something else I am overlooking? Or do you think it's perhaps just not kosher to modify original files?

**Comment by Toutouwai** [comment]
Overwriting someone else's file makes me a bit nervous because there's a small chance that something goes wrong, the file gets borked and code is lost. But if we check first for writeability and make a backup of the file then maybe that's safe enough?

Something like this:
```php
protected function addNamespace($actionPath) {
    $files = $this->wire()->files;
    $config = $this->wire()->config;

    $actionPath = str_replace('\\', '/', $actionPath);
    if(!is_writable($actionPath)) return $actionPath;

    $parts = pathinfo($actionPath);
    $backupDir = $parts['dirname'] . '/backup/';
    if(!is_dir($backupDir)) $files->mkdir($backupDir);
    $files->copy($actionPath, $backupDir . $parts['basename']);

    $contents = $files->fileGetContents($actionPath);
    $contents = substr_replace($contents, ' namespace ProcessWire;', 5, 0);
    $files->filePutContents($actionPath, $contents);
    $filePath = str_replace($config->paths->root, '/', $actionPath);
    $backupDirPath = str_replace($config->paths->root, '/', $backupDir);
    $this->wire()->warning(sprintf($this->_('The ProcessWire namespace has been added to action file %s. A backup has been copied to %s.'), $filePath, $backupDirPath), Notice::noGroup);
    return $actionPath;
}
```

BTW, I'm seeing an error notice "Undefined index: core" for this line: https://github.com/adrianbj/ProcessAdminActions/blob/77d8b7dbd4d18cd28aa4d445a430c0862ee5c15e/ProcessAdminActions.module.php#L703

**Comment by Toutouwai** [comment]
Or maybe this is better, in case AdminActions searches subfolders for action files?

```php
protected function addNamespace($actionPath) {
    $files = $this->wire()->files;
    $config = $this->wire()->config;

    $actionPath = str_replace('\\', '/', $actionPath);
    if(!is_writable($actionPath)) return $actionPath;
    $files->copy($actionPath, $actionPath . '.backup');

    $contents = $files->fileGetContents($actionPath);
    $contents = substr_replace($contents, ' namespace ProcessWire;', 5, 0);
    $files->filePutContents($actionPath, $contents);
    $filePath = str_replace($config->paths->root, '/', $actionPath);
    $this->wire()->warning(sprintf($this->_('The ProcessWire namespace has been added to action file %s. A backup of the original has been made as %s.'), $filePath, $filePath . '.backup'), Notice::noGroup);
    return $actionPath;
}
```

**Comment by adrianbj** [comment]
I like this approach better, thanks. However, with either of these, adding the namespace to the top of the file has the potential to break an action if it instantiates a core PHP class without a preceding slash, eg `new DateTime()` will result in a class not found error. Mmmmm.........

**Comment by Toutouwai** [comment]
Good point. I'll see if I can find out any more about why the PW FileCompiler isn't working consistently.

**Comment by adrianbj** [comment]
@Toutouwai - unfortunately even the latest version is causing me problems on many sites / servers - I can't figure out why it's different - all are running the same PW version and the servers are pretty much set up the same way. I'll investigate some more, but I am starting to lose motivation on this one as I seem to be going around in circles.

I am getting `Class "ProcessAdminActions" not found` errors when it is including the compiled version of an action which looks like: `class ImportBlogExcerpts extends \ProcessWire\ProcessAdminActions {`

If you can reproduce, I'd love to hear if you have any ideas.

Thanks.

**Comment by Toutouwai** [comment]
You know, I did see an error like that for my AdminActionsUnorderedListToPages action module, and it didn't make sense to me as  the compiled file looked correct (as does the one in your example). I thought it might have been something to do with it being an action that is in module form seeing as my custom actions in /site/templates/AdminActions/ compiled in the same way and yet didn't cause any errors. So I updated the module to be namespaced and requiring ProcessAdminActions >= 0.9.0 just in case anyone else experienced that problem with the module.
https://github.com/Toutouwai/AdminActionsUnorderedListToPages/commit/db59ee457170e9454cc4cd6bcf1c0abb070adaed

But I've just now updated ProcessAdminActions to 0.9.0 on a range of different sites, both local and on different remote hosts, and everything works well even with the older non-namespaced version of AdminActionsUnorderedListToPages.

Is your ImportBlogExcerpts action in a module or is it in /site/templates/AdminActions/? You could send that action to me to see if I can reproduce the problem but I have a feeling it's going to depend on some unknown factor and won't reproduce for me here.

If you want to roll back to the earlier version of the module that's okay with me. Although the namespace thing is pretty important to me it might prove too difficult to deal with as an update to ProcessAdminActions given that there are many other users and there seems to be some mystery factor at play. With ProcessAdminActions as a source and inspiration it probably won't be too hard for me to construct a separate module just for my own use.

**Comment by adrianbj** [comment]
Hi @Toutouwai - I have implemented a solution which seems to work in all situations. It involves `touch`ing the original action file and clearing its "FileCompiler__" entry in the cache DB table. That part is good and I'm happy with that. That part that's not so great is that I still need to reload the page twice to get the newly compiled version to actually load, hence the hacky stuff you'll see here: https://github.com/adrianbj/ProcessAdminActions/commit/849c3ea3767f9b8255b6187ff19a4813dee70ee5.

There is probably a better way to do this, but in a rush this morning and wanted to get things at least working before too many people upgrade to what was a broken version.

If you have any thoughts on how to do better, please let me know.

**Comment by Toutouwai** [comment]
That's great! I'm away for a couple of days but looking forward to taking a look when I'm back. Thanks.

**Comment by Toutouwai** [comment]
@adrianbj, I don't know a way to reproduce the problem where an error is thrown despite the compiled action correctly adding the namespace ("extends \ProcessWire\ProcessAdminActions") but I know I did see it one time as I described above. 

Most sites I've tested on seem to be compiling correctly but I did find another site that exhibits the same issue I was having earlier:

>  It's like it compiles the first action correctly (e.g. it changes "extends ProcessAdminActions" to "extends \ProcessWire\ProcessAdminActions") but then it fails to do this for all the other actions in the loop. It just copies them to the FileCompiler cache but doesn't actually add any namespace and I can't work out why.

Except that it's not necessarily only a single action that compiles correctly - it can be more than one that compiles correctly but with at least one action that doesn't compile correctly. And I also learned that this never happens when only a single action is compiled (e.g. when visiting the form for a particular action). It happens when multiple actions are compiled at once, possibly via the loop in the `getActions()` method, although it seems to me that PW itself is also automatically compiling some files but I don't know what the conditions are that trigger this.

It's not a wholly satisfying end point but my takeaways are:

1\. It's best to avoid the FileCompiler whenever possible (particularly considering [new issues](https://github.com/processwire/processwire-issues/issues/1874) with it are still being reported). So it would be good if users who have created custom actions manually namespace their actions after updating ProcessAdminActions, and it most cases this will be a simple as adding `// namespace ProcessWire` at the top of the action. Maybe the module could suggest this in a message on upgrade and/or when compiling non-namespaced actions?

2\. If compiling non-namespaced actions is not a very frequent occurrence (and becomes less frequent as users namespace their custom actions) then the hacky redirect is not too bad.

Regarding your other modules and any you might release in the future: of course it's totally your call as they are your modules (and I'm very grateful to have them in any format!), but to avoid potential FileCompiler issues you could adopt a policy of requiring PW3 for your modules and namespacing them by default. AFAIK the only reason not to namespace modules is to support PW2 but that feels like ancient history at this point.

**Comment by adrianbj** [comment]
@Toutouwai  - thanks for your thoughts. I've added that warning as you suggested, and updated the readme.

I have also been following that PW issue about namespacing and I will probably start migrating my modules sooner than later - thanks for the nudge.

**Comment by Toutouwai** [comment]
@adrianbj, I just updated several sites to v0.9.2 and it's working great, thanks!

What do you think about identifying the specific actions that are missing the namespace in the warning message? Something like this:
```php
if($this->wire('user')->isSuperuser()) {
    $warning = sprintf($this->_('Action %s does not declare the ProcessWire namespace. It has been compiled for you, but please consider properly namespacing it.'), $actionName);
    $this->wire()->warning($warning, Notice::noGroup);
}
```
Then the warnings look like this:
![2024-02-22_103138](https://github.com/adrianbj/ProcessAdminActions/assets/1538852/f237cfa2-c929-4081-b6a8-8ec492790440)

(I don't actually know if it's necessary to make strings that go through message(), warning(), etc, translatable or if PW does that automatically but I've always done it that way)

**Comment by adrianbj** [comment]
Yep, good idea - thanks!

It's implemented in the latest version.
