### ISSUE TITLE
UI detail

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/ProcessAdminActions#6]
A minor, non-urgent thing to save for a rainy day...

The spacing around the notifications is a bit uneven in AdminThemeUikit:
![2018-05-05_124916](https://user-images.githubusercontent.com/1538852/39658050-cc714c1a-5062-11e8-8bce-f2766d476c0a.png)

AdminThemeDefault for comparison:
![2018-05-05_124925](https://user-images.githubusercontent.com/1538852/39658051-d9017e46-5062-11e8-9054-8bf9787a7db8.png)

**Comment by adrianbj** [comment]
Thanks @Toutouwai - this should be fixed in the latest version.
