### ISSUE TITLE
Unwanted labels for config checkboxes?

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/ProcessAdminActions#8]
This might be intentional and not a bug, but the labels for the checkboxes in the "In menu" column look like they are maybe not meant to be there.

![2019-02-24_094009](https://user-images.githubusercontent.com/1538852/53291457-7e3fed00-3818-11e9-859d-9e9c96f89c48.png)

And I noticed from a screenshot in the support thread that the labels didn't used to be there.

![586a779b1633b_screenshot2017-01-02at7_53_40am thumb png d0b5d97d7933409de398064d20f6850e](https://user-images.githubusercontent.com/1538852/53291466-9fa0d900-3818-11e9-918b-41d7d0c21490.png)

**Comment by adrianbj** [comment]
Thanks @Toutouwai - not sure why/when that started happening - I can only assume it's a change to the PW core, but https://github.com/adrianbj/ProcessAdminActions/commit/e3258dc7a567d1c17cb045669e37b2a1f2d5cdcd fixes it. 

Thanks for reporting!
