### ISSUE TITLE
[Feature Request] Allow fields inside repeater templates to be copied for the "Copy Content to Other Field" action

### ISSUE THREAD

**Issue by jlahijani** [adrianbj/ProcessAdminActions#9]
The "Copy Content to Other Field" action template dropdown does not include the __templates__ that repeaters are actually based on (ie: 'repeater_myfield1', 'repeater_myfield2', etc.).

Because of this, you can't copy the content of a field INSIDE a repeater from one of its fields to another.

It only requires the following simple change in the action file:

Line 26 from:
```"sort=name, flags!=".Template::flagSystem```

to:
```"sort=name,pageClass=''|RepeaterPage|RepeaterMatrixPage"```

I've tested it out on real data and it works fine.

I think this is very useful to have as part of this action as its more comprehensive.

**Comment by adrianbj** [comment]
Sounds good - thanks!

Would you mind submitting a PR please?

**Comment by jlahijani** [comment]
Done. Hopefully I did that right.
